In [ ]:
from urllib import request
from bs4 import BeautifulSoup
import requests
import pandas

# # 1. 선수 정보를 저장할 리스트 생성(딕셔너리)
# number = []
# name = []
# position = []
# age = []
# nation = []
# team = []
# value = []

# 1-1. 선수 정보를 저장할 리스트 생성(리스트)
player_list = list()

headers = {'user-agent' : 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36'}

for page in range(1,5):
    # 2. 웹 페이지 요청
    url = f'https://www.transfermarkt.com/spieler-statistik/wertvollstespieler/marktwertetop?page={page}'

    html = requests.get(url, headers=headers)
    print(html.status_code)

    # 3. 파싱
    soup = BeautifulSoup(html.text, 'html.parser')

    # 4. 엘리먼트 추출
    # 값을 Iterable로 넣어줘 여러 개 비교 가능
    player_info = soup.find_all('tr', class_=['odd','even'])

    # 5. 리스트에 선수 정보 저장
    for info in player_info:
##        딕셔너리 형태
#         player = info.find_all('td')
#         number.append(player[0].text)
#         name.append(player[3].text)
#         position.append(player[4].text)
#         age.append(player[5].text)
#         nation.append(player[6].img['alt'])
#         team.append(player[7].a['title'])
#         value.append(player[8].a.text)

#       리스트 형태
        player = info.find_all('td')
        number = player[0].text
        name = player[3].text
        position = player[4].text
        age = player[5].text
        nation = player[6].img['alt']
        team = player[7].a['title']
        value = player[8].a.text
        player_list.append([number, name, position, age, nation, team, value])

# # 6 DataFrame 생성(딕셔너리)
# df = pandas.DataFrame({
#     'number' : number,
#     'name' : name,
#     'position' : position,
#     'age' : age,
#     'nation' : nation,
#     'team' : team,
#     'value' : value
# })

# 6-1 DataFrame 생성(리스트)
df = pandas.DataFrame(player_list, columns=['number', 'name', 'position', 'age', 'nation', 'team', 'value'])

In [6]:
# 6. csv 파일 저장 - notebook의 상대 경로 : 현재 디렉토리
df.to_csv('market100.csv', index=False)
print('** 저장 완료 **')

** 저장 완료 **

,number,name,position,age,nation,team,value
0,1,Kylian Mbappé,Centre-Forward,24,France,Paris Saint-Germain,€180.00m
1,2,Erling Haaland,Centre-Forward,22,Norway,Manchester City,€170.00m
2,3,Jude Bellingham,Central Midfield,19,England,Borussia Dortmund,€120.00m
3,4,Vinicius Junior,Left Winger,22,Brazil,Real Madrid,€120.00m
4,5,Jamal Musiala,Attacking Midfield,20,Germany,Bayern Munich,€110.00m
...,...,...,...,...,...,...,...
95,96,Gianluigi Donnarumma,Goalkeeper,24,Italy,Paris Saint-Germain,€50.00m
96,97,Lucas Hernández,Centre-Back,27,France,Bayern Munich,€50.00m
97,98,Ivan Toney,Centre-Forward,27,England,Brentford FC,€50.00m
98,99,Marco Verratti,Central Midfield,30,Italy,Paris Saint-Germain,€50.00m
99,100,David Alaba,Centre-Back,30,Austria,Real Madrid,€50.00m